server:
  port: 8081
spring:
  application:
    name: content-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${db.host}:33061/xc402_content?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${db.password}
  cloud:
    nacos:
      server-addr: 192.168.56.1:8848

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.hasten: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
