server:
  port: 9080

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      server-addr: 192.168.56.1:8848
    gateway:
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/content/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login, /logout, /getCode, /loginWithCode

  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379


hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excluePaths:
      - /search/**
      - /users/login